### ISSUE TITLE
How to install the box offline?

### ISSUE THREAD

**Issue by reardestani** [nanobox-io/nanobox-boot2docker#6]
Hi,

I have downloaded the **nanobox-boot2docker** from release to my computer. I was wondering if I can use the below command to install the box? Is this enough or I should use other commands?

`nonabox box install path-to-directory/nanobox-boot2docker`

I can not install it using the standard way because the download fails.

**Comment by glinton** [comment]
Since our box is hosted on [atlas](https://atlas.hashicorp.com/nanobox/boxes/boot2docker), you can just use `vagrant box add nanobox/boot2docker` to download the box.  The problem with adding the box from a local file, is that vagrant has a more difficult time keeping track of the box's version when it comes time to update it.
